name: CI

on:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  xcodebuild-test:
    name: xcodebuild-test
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v6
    - name: Clean Derived Data
      shell: bash
      run: |
        rm -rf ~/.derivedData
